#include "functions\Attack\dropCC.au3"
#include "functions\Attack\dropHeroes.au3"
#include "functions\Attack\GoldElixirChange.au3"
#include "functions\Attack\PrepareAttack.au3"
#include "functions\Attack\ReturnHome.au3"
#include "functions\Attack\NameOfTroop.au3"
#include "functions\Attack\SpellDarkStorage.au3"
#include "functions\Attack\Attack Algorithms\algorithmTH.au3"
#include "functions\Attack\Attack Algorithms\algorithm_AllTroops.au3"
#include "functions\Attack\Attack Algorithms\algorithm_Barch.au3"

#include "functions\Config\applyConfig.au3"
#include "functions\Config\readConfig.au3"
#include "functions\Config\saveConfig.au3"
#include "functions\Config\ScreenCoordinates.au3"
#include "functions\Config\saveloadConfig.au3"

#include "functions\Image Search\ImageSearch.au3"
#include "functions\Image Search\checkDeadBase.au3"
#include "functions\Image Search\checkTownhall.au3"
#include "functions\Image Search\checkWall.au3"
#include "functions\Image Search\checkDarkElix.au3"

#include "functions\Main Screen\checkMainScreen.au3"
#include "functions\Main Screen\checkObstacles.au3"
#include "functions\Main Screen\waitMainScreen.au3"
#include "functions\Main Screen\ZoomOut.au3"

#include "functions\Other\_Sleep.au3"
#include "functions\Other\Click.au3"
#include "functions\Other\CreateLogFile.au3"
#include "functions\Other\FindPos.au3"
#include "functions\Other\getBSPos.au3"
#include "functions\Other\SetLog.au3"
#include "functions\Other\Tab.au3"
#include "functions\Other\Time.au3"
#include "functions\Other\BlockInputEx.au3"
#include "functions\Other\_NumberFormat.au3"
#include "functions\Other\stuckHandler.au3"

#include "functions\Pixels\_CaptureRegion.au3"
#include "functions\Pixels\_ColorCheck.au3"
#include "functions\Pixels\_GetPixelColor.au3"
#include "functions\Pixels\_PixelSearch.au3"
#include "functions\Pixels\_MultiPixelSearch.au3"
#include "functions\Pixels\_WaitForPixel.au3"
#include "functions\Pixels\boolPixelSearch.au3"

#include "functions\Read Text\getChar.au3"
#include "functions\Read Text\getDarkElixir.au3"
#include "functions\Read Text\getDigit.au3"
#include "functions\Read Text\getDigitLarge.au3"
#include "functions\Read Text\getDigitSmall.au3"
#include "functions\Read Text\getElixir.au3"
#include "functions\Read Text\getGold.au3"
#include "functions\Read Text\getNormal.au3"
#include "functions\Read Text\getOther.au3"
#include "functions\Read Text\getTrophy.au3"
#include "functions\Read Text\getString.au3"
#include "functions\Read Text\getDigitTownHall.au3"
#include "functions\Read Text\getDigitLastRaid.au3"

#include "functions\Search\checkNextButton.au3"
#include "functions\Search\CompareResources.au3"
#include "functions\Search\GetResources.au3"
#include "functions\Search\PrepareSearch.au3"
#include "functions\Search\VillageSearch.au3"

#include "functions\Village\BoostAllBuilding.au3"
#include "functions\Village\CheckFullArmy.au3"
#include "functions\Village\CheckArmyCamp.au3"
#include "functions\Village\Collect.au3"
#include "functions\Village\DonateCC.au3"
#include "functions\Village\DropTrophy.au3"
#include "functions\Village\isGoldFull.au3"
#include "functions\Village\isElixirFull.au3"
#include "functions\Village\LocateBuildings.au3"
#include "functions\Village\ReArm.au3"
#include "functions\Village\RequestCC.au3"
#include "functions\Village\Train.au3"
#include "functions\Village\BotCommand.au3"
#include "functions\Village\UpgradeWall.au3"
#include "functions\Village\UpgradeBuilding.au3"
#include "functions\Village\VillageReport.au3"
#include "functions\Village\CreateSpell.au3"
#include "functions\Village\TrainDark.au3"
#include "functions\Village\TrainCustom.au3"
#include "functions\Village\CheckCostPerSearch.au3"

#include "functions\Notification\PushBullet.au3"
